# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            docker build -f dockerfile -t gitrends .
            docker tag gitrends $DOCKERHUB_USERNAME/gitrends-front-end:latest
            docker push $DOCKERHUB_USERNAME/gitrends-front-end:latest
  
workflows:
  version: 2
  workflow:
    jobs:
    - build
